# TravisCI config file. See http://travis-ci.org
language: python


python:
  - 2.6
  - 2.7

before_script:
  - mysql -e 'create database b3_test;'

env:
  global: MYSQL_TEST_HOST=127.0.0.1 MYSQL_TEST_USER=travis MYSQL_TEST_PASSWORD=travis MYSQL_TEST_DB=b3_test
  matrix:
    - B3_REPO='git+git://github.com/BigBrotherBot/big-brother-bot.git@master#egg=b3'
    - B3_REPO='git+git://github.com/BigBrotherBot/big-brother-bot.git@release-1.10#egg=b3'

before_script:
  - mysql -e "SET PASSWORD FOR travis = PASSWORD('travis');"


# command to install dependencies, e.g. pip install -r requirements.txt 
install:
  - pip install unittest2 mockito mock mysql-python
  - pip install -e ${B3_REPO}

# command to run tests, e.g. python setup.py test
script: PYTHONPATH=extplugins nosetests --where=tests --verbosity=3

notifications:
     email:
         recipients:
             - vidyac.raghav@gmail.com
             
         on_success: change
         on_failure: always

build_image: drydock/u14pytpls:prod
